### ISSUE TITLE
Reference file path should be relative to the the file it is run from

### ISSUE THREAD

**Issue by oxinabox** [Evizero/ReferenceTests.jl#16]
I got caught of guard just now,
because all my tests are `PKG/test/`,
and my references are in `PKG/test/references/`

But I ran my tests from `PKG`.
And ended up creating a bunch of tests in `PKG/references`.

`@__DIR__` should allow for this change

**Comment by Evizero** [comment]
interessting. I actually thought we used `@__DIR__`

**Comment by oxinabox** [comment]
I was doing something silly.
I forgot I moved a file.
