### ISSUE TITLE
Cut down on the dependencies

### ISSUE THREAD

**Issue by oxinabox** [Evizero/ReferenceTests.jl#5]
According to JuliaObsverver 
ReferenceTests.jl has 55 dependencies (5 direct).

For comparison: TensorFlow.jl has 30 (13 direct).
DifferentialEquations has 84 (26 direct).

It would be really nice not to be haulling down the whole Images ecosystem when doing a reference test on plain text.

I'm not sure what the current state of the optional dependencies setup is.
I'm not sure how happy [Requires.jl](https://github.com/MikeInnes/Requires.jl) is with precompilation etc,
or what is going on in the Pkg3 space with regards to it.

But anyway, it is rather annoying that every time I run a test huge amounts of time is spent cloning then removing packages.
Because I tend to list ReferenceTests.jl as a Test time dependency only.
(On my local boxes I really need to remember to install it)

**Comment by Evizero** [comment]
fair enough. I think that might be `Images.jl`. I don't even think i need it with the current code. probably could get away with only requiring ImageTransformations without any code changes

**Comment by Evizero** [comment]
I tracked down the reason for the Images dependency: https://github.com/JuliaImages/Images.jl/blob/master/src/algorithms.jl#L327-L343

Not quite sure how to go about this. maybe `Requires`

**Comment by Evizero** [comment]
What if we split this package into `ReferenceTests` and `ImageReferenceTests`, where the later depends on the former?

**Comment by oxinabox** [comment]
Requires.jl feels better to me.

It is a choice between:

```
using ReferenceTests
using Images
```

vs

```
using ImageReferenceTests
```

For some reason my gut leans towards the former.

OTOH, while Requires.jl is now more matured and less hacky (or so I am told),
it still doesn't work great with version specification AFAIK.
